SELECT DISTINCT I.NUMPED PEDIDO ,I.CODPROD CODIGO ,C.DESCRICAO PRODUTO
,CASE WHEN P.NUMNEGOCIACAO IN ('-5','-4','-3','-2') THEN 'Em negociação'
WHEN P.NUMNEGOCIACAO IN ('-1') THEN 'TIPO N'
WHEN P.NUMNEGOCIACAO IN ('0') THEN 'Sem negociação'
WHEN P.NUMNEGOCIACAO IN ('1') THEN 'Negociação'
WHEN P.NUMNEGOCIACAO IN ('2') THEN 'Aprovado'
WHEN P.NUMNEGOCIACAO IN ('3') THEN 'Saldo'
WHEN P.NUMNEGOCIACAO IN ('4','5','6') THEN 'Aguardando recebimento'
ELSE 'ERROR' END STATUS
,CASE WHEN P.NUMNEGOCIACAO NOT IN ('-5','-4','-3','-2','0','1')
THEN P.DTPREVENT  ELSE NULL END DTPREVISAO
FROM PCPEDIDO P, PCITEM I, PCPRODUT C  
WHERE I.NUMPED = P.NUMPED  AND C.CODPROD = I.CODPROD  AND C.CODFORNEC = P.CODFORNEC 
AND I.QTENTREGUE < I.QTPEDIDA AND P.VLENTREGUE < P.VLTOTAL   AND C.CODPROD = :CODPROD ;
