CREATE OR REPLACE FORCE EDITIONABLE VIEW "CARDOSO"."VW_ETIQUETA_PCTABPR" ("CODPROD", "DESCRICAO", "UNIDADE", "CODFORNEC", "CODAUXILIAR", "CODFAB", "CODEPTO", "CODSEC", "QTEST", "QTESTGER","QTRESERV", "QTBLOQUEADA", "QTINDENIZ", "QTPENDENTE", "MODULO", "RUA",
 "APTO", "NUMERO", "NUMREGIAO", "PTABELA", "PVENDA", "PTABELA1", "DTULTALTPVENDA", "DTULTALTPTABELA", "ROTINA", "DELETE") AS
  SELECT P.CODPROD
,P.DESCRICAO
,P.UNIDADE
,P.CODFORNEC
,P.CODAUXILIAR
,P.CODFAB
,P.CODEPTO
,P.CODSEC
,E.QTEST
,E.QTESTGER
,E.QTRESERV
,E.QTBLOQUEADA
,E.QTINDENIZ
,E.QTPENDENTE
,E.MODULO
,E.RUA
,E.APTO
,E.NUMERO
,C.NUMREGIAO
,C.PTABELA
,C.PVENDA
,C.PTABELA1
,C.DTULTALTPVENDA
,C.DTULTALTPTABELA
,C.ROTINA
,' ' AS DELET3
FROM PCPRODUT P, PCEST E, PCTABPR C 
WHERE P.CODPROD = E.CODPROD
AND P.CODPROD = C.CODPROD 
AND P.DTEXCLUSAO IS NULL
AND E.CODFILIAL = 1
AND C.NUMREGIAO = 1
 
